default: &default
  adapter: <%= ENV.fetch("DB_ADAPTER", "postgresql") %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  username: <%= ENV.fetch("DB_USERNAME", "ubuntu") %>
  password: <%= ENV.fetch("DB_PASSWORD", "password") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

development:
  <<: *default
  database: rubyci_homepage_development

test:
  <<: *default
  database: rubyci_homepage_test

production:
  <<: *default
  <% if ENV.fetch("DB_ADAPTER", "postgresql") == "sqlite3" %>
  database: <%= ENV.fetch("SQLITE_PATH", "db/production.sqlite3") %>
  <% else %>
  url: <%= ENV["DATABASE_URL"] %>
  <% end %>